volumes:
  mongodb_data:
    driver: local
  openldap_data:
  openldap_config:

services:
  rocketchat:
    image: rocket.chat:8
    restart: unless-stopped
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      ROOT_URL: http://localhost:3000
      PORT: 3000
      DEPLOY_METHOD: docker
      ADMIN_USERNAME: rocketadmin
      ADMIN_PASS: admin
      ADMIN_EMAIL: admin@example.com
    depends_on:
      mongodb:
        condition: service_healthy
      mongodb-bootstrap:
        condition: service_completed_successfully
    expose:
      - 3000
    ports:
      - "0.0.0.0:3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:3000/api/info', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "0.0.0.0:27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  # One-shot контейнер для инициализации MongoDB в режиме replica set
  mongodb-bootstrap:
    image: mongo:8
    restart: no
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ../../mongodb/bootstrap:/bootstrap:ro
    entrypoint: [ "/bin/bash" ]
    command: [ "/bootstrap/init.sh" ]

  # https://github.com/bitnami/containers/issues/83267
  # Альтернатива - https://github.com/nfrastack/container-openldap
  openldap:
    image: nfrastack/openldap:2.6
    restart: unless-stopped
    ports:
      - "0.0.0.0:8389:389"
    environment:
      - TZ=Europe/Moscow
      - DOMAIN=moevm.info
      - ADMIN_PASS=admin
      - BASE_DN=dc=moevm,dc=info
      - REMOVE_CONFIG_AFTER_SETUP=FALSE
      - ENABLE_BACKUP=FALSE
      - ENABLE_PPOLICY=FALSE
      - ENABLE_TLS=FALSE
      - ENABLE_REPLICATION=FALSE
    volumes:
      - openldap_data:/data/db
      - openldap_config:/data/config
    healthcheck:
      test: [ "CMD", "ldapwhoami", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=moevm,dc=info", "-w", "admin" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # One-shot контейнер для инициализации openldap данными из init.ldif
  openldap-bootstrap:
    image: nfrastack/openldap:2.6
    restart: no
    environment:
      - TZ=Europe/Moscow
      - LDAPNOINIT=1 # Отключаем автоматическую загрузку конфигов
      - ADMIN_PASS=admin
      - BASE_DN=dc=moevm,dc=info
    depends_on:
      openldap:
        condition: service_healthy
    volumes:
      - ../../openldap/bootstrap:/bootstrap:ro
    entrypoint: [ "/bin/bash" ]
    command: [ "/bootstrap/init.sh" ]
